# Generated by Django 3.1.5 on 2021-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
    ]
